{
 "title": "envoy-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Count total downstream request",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_http_app_downstream_cx_http1_total)"
    }
   ]
  },
  {
   "title": "Frontend-requests-count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_cluster_frontend_external_upstream_rq_2xx{app=\"edge-envoy\"})"
    }
   ]
  },
  {
   "title": "Total downstream requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_http_app_downstream_cx_http1_total"
    }
   ]
  },
  {
   "title": "frontend-upstream-requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_frontend_external_upstream_rq_2xx{app=\"edge-envoy\"}"
    }
   ]
  },
  {
   "title": "Admin requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_http_admin_downstream_rq_2xx{app=\"edge-envoy\"}"
    }
   ]
  }
 ]
}